feat: Added bucket encryption type
cloudquery/cq-provider-gcp pull request #181
Opened 2022-04-04 15:38 UTC by zagronitay

2022-04-04 17:44 UTC, bbernays requested changes

2022-04-04 17:44 UTC, bbernays commented on resources/services/storage/storage_buckets.go
> +	}
I don't think we are checking the casting any more...

2022-04-05 06:45 UTC, roneli approved these changes
LGTM, update the golang lint ci manually here, so tests will pass.

2022-04-06 14:16 UTC, roneli commented
Closes https://github.com/cloudquery/cq-provider-gcp/issues/180

2022-04-06 14:48 UTC, merged