feat: Added InstanceGroups
cloudquery/cq-provider-gcp pull request #186
Opened 2022-04-11 10:30 UTC by amanenk

- added istanceGroups

closes #127

2022-04-12 07:16 UTC, zagronitay requested changes
minor changes

2022-04-12 07:28 UTC, roneli requested changes

2022-04-12 07:28 UTC, roneli commented on resources/services/compute/instance_groups.go
> +				Type:        schema.TypeString,
convert to timestamp?

2022-05-09 10:05 UTC, roneli approved these changes

2022-05-09 10:08 UTC, zagronitay reviewed
LGTM, 1 question

2022-05-10 06:31 UTC, zagronitay approved these changes
LGTM

2022-05-10 08:45 UTC, merged