fix: Adjusted bigquery error when projectName used instead of projectId
cloudquery/cq-provider-gcp pull request #314
Opened 2022-06-02 12:07 UTC by amanenk

…of projectId

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

Big query API returns "The project <project_id> has not enabled BigQuery." error with type INVALID_ARGUMENT when user uses project name instead of project id. All the other resources work fine and does not give this kind of error.  
The fix changes the status of error when it happens and adds more details for user.

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

2022-06-02 12:24 UTC, erezrokah approved these changes
Looks great with a small `take it or leave it` suggestion on wording

2022-06-02 12:24 UTC, erezrokah commented on resources/services/bigquery/bigquery_datasets.go
> +					diag.WithDetails("Project name might used instead of project id"))
```suggestion
					diag.WithDetails("Please verify the project id was configured correctly. Project names can't be used when fetching BigQuery resources"))
```

2022-06-02 12:27 UTC, yevgenypats requested changes
Maybe it is correct but can you elaborate more on this fix? because as far as I can see the error is because of disabled apis and not sure it is because of name related stuff?

2022-06-06 06:27 UTC, yevgenypats approved these changes

2022-06-06 06:57 UTC, merged